### ISSUE TITLE
private and public IP addresses are not returned. 

### ISSUE THREAD

**Issue by Vad1mo** [synapticloopltd/scaleway-java-api#3]
When qurying the api and trying to get the  public Ip address the result is always Null.

The error is that the class `ServerBases` defines:
`@JsonProperty("public_ip")           private IP publicIP;`  Note **IP** is all cap

The class `Server` defines  
`@JsonProperty("public_ip")          private IP publicIp;`  Note the only letter **I** is in cap.

This results that `publicIp` is filled but `publicIP`is displayed.

Also the `privateIp` is a string whereas `publicIp` is an class of type `IP`. Is there a reason for this inconsistency?

**Comment by synapticloop** [comment]
Have made it more consistent - now
`getPrivateIp()` and `getPublicIp()`

privateIp always returns a string, whereas the public IP returns either null, or an IP object - which contains the ID of IP address, the address and whether it is dynamic.
```
"public_ip": {
    "dynamic": true,
    "id": "3d53d1de-4d3d-13d1-de4d-3d53d1de4d3d",
    "address": "212.47.227.255"
},
```

Version 0.10.2
